spring.application.name=BankingTransactionSystem




spring.datasource.url=jdbc:mysql://localhost:3306/bbankingTransactionSystem
spring.datasource.username=root
spring.datasource.password=chinna



#JPA SETTINGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
